### ISSUE TITLE
Hole in FDK reconstruction with data overlap

### ISSUE THREAD

**Issue by Thibault-Pelletier** [RTKConsortium/RTK#392] opened 2020-11-24 13:55 UTC
Hi,

I'm trying to reconstruct CBCT images with a large detector offset and overlap in the projection images.
The output geometry seems good, but there is a hole at the center of the reconstruction which I haven't been able to correct at this point.

I'm looking for any insight on how to improve the reconstruction.

Geometry : 

- Projection number : 509
- Projection resolution : 888x1096x509
- Projection frame width : 213 mm
- Projection frame height : 263 mm
- Detector distance: 638 mm
- Isocenter distance : 430 mm
- First angle : 160 °
- X detector : 99.36 mm
- Y detector : -3.6 mm
- X source : -0.24 mm
- Y source : -3.6 mm
- Angular arc: 360 °
- Origin : -106, -131, 0
- In plane angle : 0.62°
- Out of plane angle : -8.6°
- Output resolution : 1100x1100x740
- Output spacing : 0.36x0.36x0.36

Reconstruction pipeline : 

- ProjectionsReader from GGO
- CudaDisplacedDetectorImageFilter
- Also tested with DisplacedDetectorForOffsetFieldOfViewImageFilter
- CudaParkerShortScanImageFilter
- ConstantImageSource
- CudaFDKConeBeamReconstructionFilter
- StreamingImageFilter
- FieldOfViewImageFilter
- ImageFileWriter

Output : 

- Hole / white spot at the center of the reconstruction

Output reconstruction (Coronal Simplified) : 

![image](https://user-images.githubusercontent.com/58782295/100102685-3e31f200-2e64-11eb-844a-21d711c1e267.png)

Output reconstruction (Top view of the cylinder FOV):

![image2](https://user-images.githubusercontent.com/58782295/100102813-66215580-2e64-11eb-8282-f9ea9b24eb36.png)

Thank's in advance,
Thibault

**Comment by SimonRit** [comment] 2020-11-24 15:58
Have you tried `DisplacedDetectorImageFilter`? I would remove the Parker filter to be sure it does not interfere...

**Comment by Thibault-Pelletier** [comment] 2020-11-24 16:36
Thank you for your feedback,
I have tried replacing the CudaDisplacedDetectorImageFilter with DisplacedDetectorImageFilter and DisplacedDetectorForOffsetFieldOfViewImageFilter while removing the Parker filter from the pipeline but I didn't see any major improvement.

**Comment by SimonRit** [comment] 2020-11-24 22:25
I seem to be able to reproduce the problem with
```
rtksimulatedgeometry -n 360 --sdd 638 --sid 430 --first 160 --proj_iso_x 99.36 --proj_iso_y -3.6 --source_x -0.24 --source_y -3.6 --out_angle -8.6 --in_angle 0.62 -o g
rtkprojectshepploganphantom -g g --spacing $(echo 213./888 | bc -l),$(echo 263/1096 | bc -l),1 -o proj.mha --dimension 888,1096,360 --origin -106,-131,0
rtkfdk -p . -r ^proj.mha$ --dimension 1100,1100,740 -g g -o fdk.mha --spacing 0.36
```
If you just reconstruct the central slice, everything seems ok
```
rtkfdk -p . -r ^proj.mha$ --dimension 1100,1100,740 -g g -o fdk.mha --spacing 0.36
```
So it might just be a limitation of the method...

**Comment by Thibault-Pelletier** [comment] 2020-11-25 09:49
Thank you for this analysis.
Does that mean that I should consider changing the reconstruction algorithm from FDK to another one for this case?
If so would you have recommendations on which to pick?

**Comment by SimonRit** [comment] 2020-11-26 20:26
If I'm right, yes. I think I would start with iterative reconstruction to check if the artefacts are caused by the reconstruction algorithm or by missing data. With RTK, I would use rtkconjugategradient I think but you'll need to adjust the regularization (`--gamma`) and the number of iterations (`--niterations`).

**Comment by SimonRit** [comment] 2020-12-08 08:46
I'm closing the issue, please reopen if you think there is something wrong with RTK.

**Closed as completed by SimonRit** 2020-12-08 08:46 UTC
