### ISSUE TITLE
When reconstructing with rtk, the cuda memory is not released

### ISSUE THREAD

**Issue by qingwang-usc** [RTKConsortium/RTK#616] opened 2024-09-06 01:41 UTC
Hi @SimonRit , recently when trying to FDK reconstruction using RTK, I noticed that the cuda memory is not released, and I would like to know if there is some way to be able to release the cuda memory after each reconstruction?
<img width="598" alt="联想截图_20240906094056" src="https://github.com/user-attachments/assets/21d6181e-5faf-4c09-a419-9aef2c82f719">

**Comment by SimonRit** [comment] 2024-09-06 07:19
Hi @qingwang-usc,
This is a duplicate of #612 which has been fixed (hopefully). This was a bug, sorry, which has been [fixed](https://github.com/RTKConsortium/RTK/commit/06d355709cc0273ff771b64746e008e45f5e66dd). I'm closing but please re-open if upgrading to master does not fix the bug. Note that you'll soon be able to use the CI python packages as soon as they finish compiling, available as artifacts [here](https://github.com/RTKConsortium/RTK/actions/runs/10685686621).

**Closed as completed by SimonRit** 2024-09-06 07:19 UTC

**Comment by qingwang-usc** [comment] 2024-09-06 10:36
Thanks for the reply, but I'm still a bit confused on how to fix this bug. Should I modify the src/rtkCudaUtilities.cu file or recompile the RTK?

**Comment by SimonRit** [comment] 2024-09-06 13:15
If you compile RTK, you should update the sources to the master's HEAD and recompile. If you use the pypi Python package, you should download a Python package availabe from the CI [here](https://github.com/RTKConsortium/RTK/actions/runs/10685686621) and install it.
